/**
 * IndexedDB-backed local draft for same-device resume.
 *
 * Design constraints from the design doc (section 5e) and the accepted 0004/
 * 0005 workflow decisions:
 *   - Written after every response.
 *   - Keyed by the session UUID from `start_session()`.
 *   - On load, if an incomplete draft exists, NEVER silently resume — a shared
 *     school computer could otherwise hand Student A's in-progress test to
 *     Student B. TestRunner is responsible for asking before resuming; this
 *     module only stores/retrieves.
 *   - Not cleared until the server confirms a fully successful submit_session()
 *     call. A failed submit must leave the draft intact so a retry has
 *     something to retry with.
 *   - The screening code is generated by start_session() at the very start
 *     (needed as this resume anchor) but is only ever DISPLAYED to the student
 *     at the closing screen — see PHASE_1_REPORT.md's G2 workflow note: writing
 *     it down at start risks a stale code on paper if the session is abandoned
 *     and restarted.
 *   - Cross-device recovery is out of scope for v1 — only one draft is ever
 *     kept, for the current device.
 *
 * IndexedDB (not localStorage) because recorded audio Blobs need to be stored
 * as binary, not serialised to a string, and because localStorage's ~5MB quota
 * would not survive a battery's worth of recordings.
 */

const DB_NAME = 'badsq-draft';
const DB_VERSION = 1;
const STORE = 'draft';
const SINGLETON_KEY = 'current';

export type ResponseDraft = {
  itemId: string;
  responseClientId: string; // stable across retries; also the audio storage filename stem
  selectedOptionKey: string | null;
  typedValue: string | null;
  audioBlob: Blob | null;
  audioMimeType: string | null;
  audioDurationMs: number | null;
  stimulusFirstEndClientTs: number | null;
  stimulusLastEndClientTs: number | null;
  responseClientTs: number | null;
  responseLatencyFromFirstMs: number | null;
  responseLatencyFromLastMs: number | null;
  inputModality: 'touch' | 'mouse' | 'pen' | 'keyboard' | 'unknown' | null;
  viewportWidth: number | null;
  viewportHeight: number | null;
  /**
   * NULL means "this item has no instruction/stimulus audio at all", distinct
   * from 0 ("it has audio, never replayed"). See migration 0011.
   */
  replayCountInstruction: number | null;
  replayCountStimulus: number | null;
  technicalRetryCount: number;
  /** Set on first interaction; timing/modality fields freeze after this. */
  hasAnswered: boolean;
};

/** Background info + consent-replication answers -- collected before the test
 * starts, with no time tracking (see TestRunner's 'background-info' and
 * 'consent-questions' phases). */
export type BackgroundInfo = {
  ageYears: number | null;
  gender: 'boy' | 'girl' | 'prefer_not_to_say' | null;
  homeArea: 'urban' | 'rural' | null;
};

/** Mirrors the three family-history questions on the paper parental-consent
 * form -- the participant re-selects what their parent already marked there. */
export type ConsentAnswers = {
  q1DoctorEval: boolean | null;
  q1SchoolEval: boolean | null;
  q1NotSure: boolean | null;
  q2ExtraPrimarySupport: 'yes' | 'no' | 'not_sure' | null;
  q3FamilyHistory: 'yes' | 'no' | 'not_sure' | null;
};

export type LocalDraft = {
  sessionId: string;
  assignedCode: string;
  startedAtMs: number;
  classGrade: 6 | 7 | 8 | null;
  background: BackgroundInfo;
  consent: ConsentAnswers;
  currentItemIndex: number;
  responses: Record<string, ResponseDraft>;
};

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE);
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error ?? new Error('Could not open IndexedDB'));
  });
}

async function withStore<T>(mode: IDBTransactionMode, fn: (store: IDBObjectStore) => IDBRequest<T>): Promise<T> {
  const db = await openDb();
  try {
    return await new Promise<T>((resolve, reject) => {
      const tx = db.transaction(STORE, mode);
      const req = fn(tx.objectStore(STORE));
      req.onsuccess = () => resolve(req.result);
      req.onerror = () => reject(req.error ?? new Error('IndexedDB request failed'));
    });
  } finally {
    db.close();
  }
}

export async function loadDraft(): Promise<LocalDraft | null> {
  const result = await withStore<LocalDraft | undefined>('readonly', (s) => s.get(SINGLETON_KEY));
  return result ?? null;
}

export async function saveDraft(draft: LocalDraft): Promise<void> {
  await withStore<IDBValidKey>('readwrite', (s) => s.put(draft, SINGLETON_KEY));
}

export async function clearDraft(): Promise<void> {
  await withStore<undefined>('readwrite', (s) => s.delete(SINGLETON_KEY));
}

export function newEmptyDraft(sessionId: string, assignedCode: string): LocalDraft {
  return {
    sessionId,
    assignedCode,
    startedAtMs: Date.now(),
    classGrade: null,
    background: { ageYears: null, gender: null, homeArea: null },
    consent: {
      q1DoctorEval: null,
      q1SchoolEval: null,
      q1NotSure: null,
      q2ExtraPrimarySupport: null,
      q3FamilyHistory: null,
    },
    currentItemIndex: 0,
    responses: {},
  };
}

/** Has every item in `itemIds` got a recorded answer? Gates the Submit button. */
/**
 * Does this response carry a real answer, not just a timing anchor?
 *
 * An empty string is NOT an answer. This matters: NUMERIC_KEYPAD/LETTER_SPAN
 * call onChange('') when the participant presses ⌫ or C, so a bare
 * `typedValue !== null` check would treat "typed a digit, then cleared it" as
 * answered — which let a participant advance having entered nothing at all.
 * Single source of truth for both the per-item Next gate (TestRunner's
 * canAdvance) and the whole-session submit gate below, so the two can never
 * disagree about what counts as answered.
 */
export function hasRealAnswer(r: ResponseDraft): boolean {
  if (r.audioBlob !== null) return true;
  if (r.selectedOptionKey !== null && r.selectedOptionKey.trim() !== '') return true;
  if (r.typedValue !== null && r.typedValue.trim() !== '') return true;
  return false;
}

export function allAnswered(draft: LocalDraft, itemIds: string[]): boolean {
  return itemIds.every((id) => {
    const r = draft.responses[id];
    if (!r || !r.hasAnswered) return false;
    return hasRealAnswer(r);
  });
}
