/**
 * IndexedDB-backed local draft for same-device resume.
 *
 * Design constraints from the design doc (section 5e) and the accepted 0004/
 * 0005 workflow decisions:
 *   - Written after every response.
 *   - Keyed by the session UUID from `start_session()`.
 *   - On load, if an incomplete draft exists, NEVER silently resume — a shared
 *     school computer could otherwise hand Student A's in-progress test to
 *     Student B. TestRunner is responsible for asking before resuming; this
 *     module only stores/retrieves.
 *   - Not cleared until the server confirms a fully successful submit_session()
 *     call. A failed submit must leave the draft intact so a retry has
 *     something to retry with.
 *   - The screening code is generated by start_session() at the very start
 *     (needed as this resume anchor) but is only ever DISPLAYED to the student
 *     at the closing screen — see PHASE_1_REPORT.md's G2 workflow note: writing
 *     it down at start risks a stale code on paper if the session is abandoned
 *     and restarted.
 *   - Cross-device recovery is out of scope for v1 — only one draft is ever
 *     kept, for the current device.
 *
 * IndexedDB (not localStorage) because recorded audio Blobs need to be stored
 * as binary, not serialised to a string, and because localStorage's ~5MB quota
 * would not survive a battery's worth of recordings.
 */

const DB_NAME = 'badsq-draft';
const DB_VERSION = 1;
const STORE = 'draft';
const SINGLETON_KEY = 'current';

export type ResponseDraft = {
  itemId: string;
  responseClientId: string; // stable across retries; also the audio storage filename stem
  selectedOptionKey: string | null;
  typedValue: string | null;
  audioBlob: Blob | null;
  audioMimeType: string | null;
  audioDurationMs: number | null;
  stimulusFirstEndClientTs: number | null;
  stimulusLastEndClientTs: number | null;
  responseClientTs: number | null;
  responseLatencyFromFirstMs: number | null;
  responseLatencyFromLastMs: number | null;
  inputModality: 'touch' | 'mouse' | 'pen' | 'keyboard' | 'unknown' | null;
  viewportWidth: number | null;
  viewportHeight: number | null;
  /**
   * NULL means "this item has no instruction/stimulus audio at all", distinct
   * from 0 ("it has audio, never replayed"). See migration 0011.
   */
  replayCountInstruction: number | null;
  replayCountStimulus: number | null;
  technicalRetryCount: number;
  /**
   * How many times the participant changed their answer before advancing.
   * The column has existed since migration 0007 but nothing ever wrote it, so
   * it exported as a constant 0 -- a field that looked like data and was not.
   */
  selectionChangeCount: number;
  /**
   * performance.timeOrigin for the page load that produced the timestamps in
   * this draft. performance.now() restarts at zero on every page load, so
   * after a resume the *ClientTs values below are NOT comparable with those
   * recorded before the reload. Storing the origin makes them absolute again
   * (origin + ts) and makes the reload itself visible in the data.
   */
  clientTimeOriginMs: number | null;
  /** Set on first interaction; timing/modality fields freeze after this. */
  hasAnswered: boolean;
};

/** Background info + consent-replication answers -- collected before the test
 * starts, with no time tracking (see TestRunner's 'background-info' and
 * 'consent-questions' phases). */
export type BackgroundInfo = {
  ageYears: number | null;
  gender: 'boy' | 'girl' | 'prefer_not_to_say' | null;
  homeArea: 'urban' | 'rural' | null;
};

/** Mirrors the three family-history questions on the paper parental-consent
 * form -- the participant re-selects what their parent already marked there. */
export type ConsentAnswers = {
  q1DoctorEval: boolean | null;
  q1SchoolEval: boolean | null;
  q1NotSure: boolean | null;
  q2ExtraPrimarySupport: 'yes' | 'no' | 'not_sure' | null;
  q3FamilyHistory: 'yes' | 'no' | 'not_sure' | null;
};

export type LocalDraft = {
  sessionId: string;
  assignedCode: string;
  startedAtMs: number;
  /**
   * Wall clock of the last write, stamped by saveDraft() itself so it cannot
   * drift from reality no matter which caller persisted. Drives the staleness
   * check below. Optional only for drafts written before this field existed --
   * isDraftStale() falls back to startedAtMs for those.
   */
  updatedAtMs?: number;
  /**
   * Stamped the moment a submit is first attempted, i.e. when the draft stops
   * being "a test in progress" and becomes "a finished session awaiting
   * upload". Exempts the draft from the resume window — see isDraftStale().
   */
  sealedAtMs?: number;
  classGrade: 6 | 7 | 8 | null;
  background: BackgroundInfo;
  consent: ConsentAnswers;
  currentItemIndex: number;
  responses: Record<string, ResponseDraft>;
};

/**
 * How long a draft stays resumable after its last write.
 *
 * DELIBERATELY SHORT (3 minutes, not the 30 originally chosen). The
 * class/gender identity re-check in TestRunner (see handleResumeYes) is
 * close to useless in a room that is one class and one gender -- every
 * student answers it identically, so it cannot actually distinguish Student
 * A from Student B on a device handed between them. Expiry is therefore the
 * REAL guard in that setting, not a backstop for it: a device physically
 * handed to the next student takes longer than 3 minutes in practice, while
 * a dropped connection during a live question is usually reconnected within
 * seconds. Expiring on inactivity is what stops Student B from ever being
 * offered Student A's session, without depending on either a child reading
 * the resume prompt correctly or the identity check meaning anything.
 *
 * The real cost: a genuine interruption that takes LONGER than 3 minutes to
 * resolve (a stuck app, a supervisor dealing with something else, a longer
 * connectivity drop) now loses the session and forces a full restart, where
 * the old 30-minute window would have preserved it. That trade was made
 * deliberately, in favour of the contamination risk being small.
 *
 * Measured from the last write, not from startedAtMs: a student interrupted at
 * item 60 has a draft that STARTED 40 minutes ago but was touched seconds ago,
 * and must still be resumable.
 */
export const DRAFT_STALE_AFTER_MS = 3 * 60 * 1000;

/**
 * True when a draft is too old to offer for resume. TestRunner discards these
 * silently and starts a fresh session rather than showing the resume prompt.
 *
 * A draft with neither timestamp is treated as stale: it predates both fields,
 * so there is no way to tell whose it is, and guessing wrong contaminates data.
 */
export function isDraftStale(draft: LocalDraft, nowMs: number = Date.now()): boolean {
  // A SEALED draft never expires. The window above exists to stop Student B
  // being offered Student A's half-finished test on a shared device; a sealed
  // draft is not that. It is a COMPLETE session whose upload failed, and no
  // further answers can be added to it -- the only action it offers is "send
  // again", so there is nothing for a second student to contaminate.
  //
  // Expiring it was a real data-loss bug: a submit that failed (no signal in
  // the exam room is the usual cause) left the draft intact, exactly as the
  // submit-error screen promises the child it does -- and then this function
  // threw it away three minutes later, silently, on the next load. A full
  // 30-40 minute session including all 17 recordings was lost that way, with
  // nothing server-side to recover from because nothing is written until
  // submit_session() succeeds.
  if (typeof draft.sealedAtMs === 'number' && Number.isFinite(draft.sealedAtMs)) return false;

  const last = draft.updatedAtMs ?? draft.startedAtMs;
  if (typeof last !== 'number' || !Number.isFinite(last)) return true;
  return nowMs - last > DRAFT_STALE_AFTER_MS;
}

/**
 * How long to wait for IndexedDB to open before giving up.
 *
 * `indexedDB.open()` can fire NEITHER success nor error: if another still-open
 * connection blocks a version change it fires `blocked` and then simply waits,
 * forever, for that other connection to close. On iOS Safari a page kept alive
 * in the back/forward cache is exactly such a connection, so hammering the
 * browser Back button can leave a fresh page hanging on an open() that never
 * settles. Without this timeout the whole test screen hangs on "Loading…".
 */
const DB_OPEN_TIMEOUT_MS = 4000;

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    let settled = false;
    const finish = (fn: () => void) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      fn();
    };

    const timer = setTimeout(
      () => finish(() => reject(new Error('IndexedDB open timed out (another tab may hold it open)'))),
      DB_OPEN_TIMEOUT_MS,
    );

    let req: IDBOpenDBRequest;
    try {
      req = indexedDB.open(DB_NAME, DB_VERSION);
    } catch (e) {
      // Safari Private Browsing and some locked-down configurations throw here
      // rather than firing onerror.
      finish(() => reject(e instanceof Error ? e : new Error('IndexedDB unavailable')));
      return;
    }

    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE);
    };
    req.onsuccess = () => finish(() => resolve(req.result));
    req.onerror = () => finish(() => reject(req.error ?? new Error('Could not open IndexedDB')));
    req.onblocked = () =>
      finish(() => reject(new Error('IndexedDB blocked by another open connection')));
  });
}

async function withStore<T>(mode: IDBTransactionMode, fn: (store: IDBObjectStore) => IDBRequest<T>): Promise<T> {
  const db = await openDb();
  try {
    return await new Promise<T>((resolve, reject) => {
      const tx = db.transaction(STORE, mode);
      const req = fn(tx.objectStore(STORE));
      req.onsuccess = () => resolve(req.result);
      req.onerror = () => reject(req.error ?? new Error('IndexedDB request failed'));
    });
  } finally {
    db.close();
  }
}

/**
 * Read the saved draft, or null when there is none.
 *
 * NEVER THROWS. The draft is a convenience (same-device resume); IndexedDB
 * being unavailable must not stop a participant from taking the test. This
 * used to reject, and TestRunner's load path had no guard around it, so a
 * blocked or failed open surfaced as "Could not load the test" and the
 * participant could not start at all. Losing the ability to resume is a far
 * smaller failure than losing the ability to begin.
 */
export async function loadDraft(): Promise<LocalDraft | null> {
  try {
    const result = await withStore<LocalDraft | undefined>('readonly', (s) => s.get(SINGLETON_KEY));
    return result ?? null;
  } catch {
    return null;
  }
}

export async function saveDraft(draft: LocalDraft): Promise<void> {
  // Stamped here rather than at each call site so no future caller can persist
  // a draft without refreshing its resume window.
  const stamped: LocalDraft = { ...draft, updatedAtMs: Date.now() };
  await withStore<IDBValidKey>('readwrite', (s) => s.put(stamped, SINGLETON_KEY));
}

export async function clearDraft(): Promise<void> {
  await withStore<undefined>('readwrite', (s) => s.delete(SINGLETON_KEY));
}

export function newEmptyDraft(sessionId: string, assignedCode: string): LocalDraft {
  return {
    sessionId,
    assignedCode,
    startedAtMs: Date.now(),
    updatedAtMs: Date.now(),
    classGrade: null,
    background: { ageYears: null, gender: null, homeArea: null },
    consent: {
      q1DoctorEval: null,
      q1SchoolEval: null,
      q1NotSure: null,
      q2ExtraPrimarySupport: null,
      q3FamilyHistory: null,
    },
    currentItemIndex: 0,
    responses: {},
  };
}

/** Has every item in `itemIds` got a recorded answer? Gates the Submit button. */
/**
 * Does this response carry a real answer, not just a timing anchor?
 *
 * An empty string is NOT an answer. This matters: NUMERIC_KEYPAD/LETTER_SPAN
 * call onChange('') when the participant presses ⌫ or C, so a bare
 * `typedValue !== null` check would treat "typed a digit, then cleared it" as
 * answered — which let a participant advance having entered nothing at all.
 * Single source of truth for both the per-item Next gate (TestRunner's
 * canAdvance) and the whole-session submit gate below, so the two can never
 * disagree about what counts as answered.
 */
export function hasRealAnswer(r: ResponseDraft): boolean {
  if (r.audioBlob !== null) return true;
  if (r.selectedOptionKey !== null && r.selectedOptionKey.trim() !== '') return true;
  if (r.typedValue !== null && r.typedValue.trim() !== '') return true;
  return false;
}

export function allAnswered(draft: LocalDraft, itemIds: string[]): boolean {
  return itemIds.every((id) => {
    const r = draft.responses[id];
    if (!r || !r.hasAnswered) return false;
    return hasRealAnswer(r);
  });
}
