/**
 * IndexedDB-backed local draft for same-device resume.
 *
 * Design constraints from the design doc (section 5e) and the accepted 0004/
 * 0005 workflow decisions:
 *   - Written after every response.
 *   - Keyed by the session UUID from `start_session()`.
 *   - On load, if an incomplete draft exists, NEVER silently resume — a shared
 *     school computer could otherwise hand Student A's in-progress test to
 *     Student B. TestRunner is responsible for asking before resuming; this
 *     module only stores/retrieves.
 *   - Not cleared until the server confirms a fully successful submit_session()
 *     call. A failed submit must leave the draft intact so a retry has
 *     something to retry with.
 *   - The screening code is generated by start_session() at the very start
 *     (needed as this resume anchor) but is only ever DISPLAYED to the student
 *     at the closing screen — see PHASE_1_REPORT.md's G2 workflow note: writing
 *     it down at start risks a stale code on paper if the session is abandoned
 *     and restarted.
 *   - Cross-device recovery is out of scope for v1 — only one draft is ever
 *     kept, for the current device.
 *
 * IndexedDB (not localStorage) because recorded audio Blobs need to be stored
 * as binary, not serialised to a string, and because localStorage's ~5MB quota
 * would not survive a battery's worth of recordings.
 */

const DB_NAME = 'badsq-draft';
const DB_VERSION = 1;
const STORE = 'draft';
const SINGLETON_KEY = 'current';

export type ResponseDraft = {
  itemId: string;
  responseClientId: string; // stable across retries; also the audio storage filename stem
  selectedOptionKey: string | null;
  typedValue: string | null;
  audioBlob: Blob | null;
  audioMimeType: string | null;
  audioDurationMs: number | null;
  stimulusFirstEndClientTs: number | null;
  stimulusLastEndClientTs: number | null;
  responseClientTs: number | null;
  responseLatencyFromFirstMs: number | null;
  responseLatencyFromLastMs: number | null;
  inputModality: 'touch' | 'mouse' | 'pen' | 'unknown' | null;
  viewportWidth: number | null;
  viewportHeight: number | null;
  replayCountInstruction: number;
  replayCountStimulus: number;
  technicalRetryCount: number;
  /** Set on first interaction; timing/modality fields freeze after this. */
  hasAnswered: boolean;
};

export type LocalDraft = {
  sessionId: string;
  assignedCode: string;
  startedAtMs: number;
  classGrade: 6 | 7 | 8 | null;
  currentItemIndex: number;
  responses: Record<string, ResponseDraft>;
};

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE);
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error ?? new Error('Could not open IndexedDB'));
  });
}

async function withStore<T>(mode: IDBTransactionMode, fn: (store: IDBObjectStore) => IDBRequest<T>): Promise<T> {
  const db = await openDb();
  try {
    return await new Promise<T>((resolve, reject) => {
      const tx = db.transaction(STORE, mode);
      const req = fn(tx.objectStore(STORE));
      req.onsuccess = () => resolve(req.result);
      req.onerror = () => reject(req.error ?? new Error('IndexedDB request failed'));
    });
  } finally {
    db.close();
  }
}

export async function loadDraft(): Promise<LocalDraft | null> {
  const result = await withStore<LocalDraft | undefined>('readonly', (s) => s.get(SINGLETON_KEY));
  return result ?? null;
}

export async function saveDraft(draft: LocalDraft): Promise<void> {
  await withStore<IDBValidKey>('readwrite', (s) => s.put(draft, SINGLETON_KEY));
}

export async function clearDraft(): Promise<void> {
  await withStore<undefined>('readwrite', (s) => s.delete(SINGLETON_KEY));
}

export function newEmptyDraft(sessionId: string, assignedCode: string): LocalDraft {
  return {
    sessionId,
    assignedCode,
    startedAtMs: Date.now(),
    classGrade: null,
    currentItemIndex: 0,
    responses: {},
  };
}

/** Has every item in `itemIds` got a recorded answer? Gates the Submit button. */
export function allAnswered(draft: LocalDraft, itemIds: string[]): boolean {
  return itemIds.every((id) => {
    const r = draft.responses[id];
    if (!r || !r.hasAnswered) return false;
    // An "answer" needs actual content, not just a timing anchor: a choice
    // format needs a selected option, NUMERIC_KEYPAD needs typed digits,
    // AUDIO_RECORD needs a captured blob.
    return r.selectedOptionKey !== null || r.typedValue !== null || r.audioBlob !== null;
  });
}
